# Generated by Django 5.0.6 on 2024-06-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title'),
            preserve_default=False,
        ),
    ]
