# Generated by Django 5.0.6 on 2024-06-02 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0010_alter_post_categories_alter_post_community_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
